import ProvidersWrapper from "./ProvidersWrapper";

ProvidersWrapper;
export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<ProvidersWrapper>{children}</ProvidersWrapper>
			</body>
		</html>
	);
}
