// RootLayout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import UnauthHeader from "@/common/components/UnauthHeader";
// import Combined from "@/common/components/CombinedSidebar/Combined";
import Login from "./Login";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

const RootLayout = () =>
  // Uncomment if needed
  // 	{ children,
  // }: {
  // 	children: React.ReactNode;
  // }): JSX.Element
  {
    return (
      <html lang="en">
        <body className={inter.className}>
          <div className="flex flex-col w-full">
            <Login/>
            {/* <UnauthHeader />
            <Combined /> */}
          </div>
        </body>
      </html>
    );
  };

export default RootLayout;
