import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import UnauthHeader from "@/common/components/UnauthHeader";
import QueryClientWrapper from "@/common/components/QueryClientWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function AccountLayout({
  children,
}: {
  readonly children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col w-full">
          <QueryClientWrapper>
            <UnauthHeader />
            {children}
          </QueryClientWrapper>
        </div>
      </body>
    </html>
  );
};
