import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryClientWrapper from "@/common/components/QueryClientWrapper";
import React from "react";
import ShadcnHeader from "@/common/components/Header";
import ShadcnSidebar from "@/common/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Turborepo",
	description: "Generated by create turbo",
};

export default async function AccountLayout({
	children,
}: {
	readonly children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex flex-col w-full">
					<QueryClientWrapper>
						<ShadcnHeader />
						<ShadcnSidebar />
						<main>{children}</main>
					</QueryClientWrapper>
				</div>
			</body>
		</html>
	);
}
