import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryClientWrapper from "@/common/components/QueryClientWrapper";
import React from "react";
import AuthLayout from "@/common/components/AuthLayout";
import AuthStateProvider from "@/common/components/AuthStateProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function AccountLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientWrapper>
<<<<<<< HEAD
            <AuthLayout>{children}</AuthLayout>
=======
        
            <AuthLayout>{children}</AuthLayout>
         
>>>>>>> 74bd52a92343da5ced9165f0c2da363eeac7fc18
        </QueryClientWrapper>
      </body>
    </html>
  );
}
