import { SESSION } from "@/common/constants/page-titles";
import SessionVerifier from "@/module/Authentication/components/SessionVerifier";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Turborepo",
	description: "Generated by create turbo",
};

const SessionTypePage = () => {
	return <SessionVerifier />;
};

export default SessionTypePage;
